In [2]:
require(data.table)
require(tidyverse)
require(phyloseq)
require(ggplot2)
require(RColorBrewer)
require(metacoder)
require(vegan)
require(DESeq2)

In [64]:
ps<-readRDS(file = "/work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/BEL_16S_ITS2/BEL_ITS2_outputs/RDS/ps_ITS2.rds")
#removing any taxa that don't show up in any samples to speed up the process
ps <- prune_taxa(taxa_sums(ps) > 0, ps)
ps

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 417 taxa and 475 samples ]
sample_data() Sample Data:       [ 475 samples by 24 sample variables ]
tax_table()   Taxonomy Table:    [ 417 taxa by 8 taxonomic ranks ]

In [65]:
#normalizing ps by converting rawcounts into relative abundances
#so samples with more reads wont be over represented
#using ps bc only to the count data (OTU table), while preserving the rest of the object
ps_norm = transform_sample_counts(ps, function(x) 1E6 * x / sum(x))

## vegan
- not sure if this is working with symportal data

In [66]:
# convert the sample_data() within a phyloseq object to a vegan compatible data object
pssd2veg <- function(ps_norm) {
  sample_veg<- sample_data(ps_norm)
  return(as(sample_veg,"data.frame"))
}
#using phyloseq nmds plot 
sample_veg <- pssd2veg(ps_norm)

In [67]:
# convert the otu_table() within a phyloseq object to a vegan compatible data object
psotu2veg <- function(ps_norm) {
  otu_veg <- otu_table(ps_norm)
    
  if (taxa_are_rows(otu_veg)) {
    otu_veg <- t(otu_veg)
  }
  return(as(otu_veg, "matrix"))
}

# Extract normalized OTU matrix and sample data
otu_veg <- psotu2veg(ps_norm)

In [68]:
head(otu_table(ps_norm))
head(otu_veg)

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2027480 2026464
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0     ⋯   0       0
                           2026486 2023928 2027858 2029769 2028086 2028835
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           2027844 2027851
012024_BEL_CBC_T1_557_SSID NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0
012024_BEL_CBC_T1_561_OANN   0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0
012024_BEL_CBC_T2_585_OFAV   0       0

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2027480 2026464
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0     ⋯   0       0
                           2026486 2023928 2027858 2029769 2028086 2028835
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           2027844 2027851
012024_BEL_CBC_T1_557_SSID NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0
012024_BEL_CBC_T1_561_OANN   0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0
012024_BEL_CBC_T2_585_OFAV   0       0

In [69]:
class(otu_veg)
class(sample_veg)

[1] "matrix" "array"

[1] "data.frame"

In [70]:
head(sample_veg)

                           Date_Extracted Raw_ng_ul Date_Enriched
012024_BEL_CBC_T1_557_SSID 2_17_2025      44.6
012024_BEL_CBC_T1_559_MCAV 2_17_2025      14.8
012024_BEL_CBC_T1_561_OANN 2_17_2025      18
012024_BEL_CBC_T1_563_PSTR 2_17_2025      35.8
012024_BEL_CBC_T1_565_PAST 2_17_2025      7.72
012024_BEL_CBC_T2_585_OFAV 2_17_2025      71.6
                           Microbe_Location Month_year colony CollectionDate
012024_BEL_CBC_T1_557_SSID                  12024      1_3    1/10/24
012024_BEL_CBC_T1_559_MCAV                  12024      1_24   1/10/24
012024_BEL_CBC_T1_561_OANN                  12024      1_25   1/10/24
012024_BEL_CBC_T1_563_PSTR                  12024      1_12   1/10/24
012024_BEL_CBC_T1_565_PAST                  12024      1_21   1/10/24
012024_BEL_CBC_T2_585_OFAV                  12024      2_76   1/12/24
                           Species Health_status   Sample_physical_location ⋯
012024_BEL_CBC_T1_557_SSID SSID    Healthy         UML_NARWHAL_R5_B18       ⋯
012024_BEL_CBC_T1_559_MCAV MCAV    Healthy         UML_NARWHAL_R5_B18       ⋯
012024_BEL_CBC_T1_561_OANN OANN    Healthy         UML_NARWHAL_R5_B18       ⋯
012024_BEL_CBC_T1_563_PSTR PSTR    Healthy         UML_NARWHAL_R5_B18       ⋯
012024_BEL_CBC_T1_565_PAST PAST    Bleached_Tissue UML_NARWHAL_R5_B18       ⋯
012024_BEL_CBC_T2_585_OFAV OFAV    Healthy         UML_NARWHAL_R5_B18       ⋯
                           Date_ITS2  Seq_run Transect sample_uid data_set_uid
012024_BEL_CBC_T1_557_SSID 7_7_2025   1       CBC30N   262771     1416
012024_BEL_CBC_T1_559_MCAV 12_15_2025 2       CBC30N   267721     1458
012024_BEL_CBC_T1_561_OANN 1_21_2026  3       CBC30N   267626     1457
012024_BEL_CBC_T1_563_PSTR 7_7_2025   1       CBC30N   262772     1416
012024_BEL_CBC_T1_565_PAST 2_17_2026  4       CBC30N   269104     1471
012024_BEL_CBC_T2_585_OFAV 2_17_2026  4       SR30N    269105     1471
                           host_family    host_genus     host_species
012024_BEL_CBC_T1_557_SSID Rhizangiidae   Siderastrea    sidera
012024_BEL_CBC_T1_559_MCAV Montastraeidae Montastrea     cavernosa
012024_BEL_CBC_T1_561_OANN Merulinidae    Orbicella      annularis
012024_BEL_CBC_T1_563_PSTR Faviidae       Pseudodiploria strigosa
012024_BEL_CBC_T1_565_PAST Poritidae      Porites        asteroides
012024_BEL_CBC_T2_585_OFAV Merulinidae    Orbicella      faveolata
                           collection_date collection_depth
012024_BEL_CBC_T1_557_SSID   202401        8
012024_BEL_CBC_T1_559_MCAV 20240110        8
012024_BEL_CBC_T1_561_OANN 20240110        8
012024_BEL_CBC_T1_563_PSTR   202401        8
012024_BEL_CBC_T1_565_PAST 20240110        8
012024_BEL_CBC_T2_585_OFAV 20240112        8

In [71]:
#save sammple names as a column so tidy doesn't get rid of it during filtering
sample_veg$SampleID <- rownames(sample_veg)

In [72]:
#changing format of Month_year to be Jan 2024 using collection date
sample_veg$CollectionDate <- as.factor(sample_veg$CollectionDate)
# Convert to Date format 
sample_veg$DateFormatted <- as.Date(paste0(sample_veg$CollectionDate), format = "%m/%d/%y")
# now will have a new column that has Month Year instead of date_sampled
sample_veg$Month_year <- format(sample_veg$DateFormatted, "%b %Y")
sample_veg$Month_year <- factor(sample_veg$Month_year, levels = unique(sample_veg$Month_year))

#MonthYear in chronological order
# 2. reorder MonthYear as a factor in chronological order
sample_veg$Month_year <- factor(sample_veg$Month_year,
        levels = unique(sample_veg$Month_year[order(sample_veg$DateFormatted)])
)

In [73]:
#clean sample_veg

 #cleaning up meta to only be of interest
sample_clean<- sample_veg[, c("SampleID", "Health_status", "colony", "Date_ITS2", "Condition", "Species", "Month_year", "Seq_run", "Transect", "sample_uid", "DateFormatted")]
head(sample_clean)

                           SampleID                   Health_status   colony
012024_BEL_CBC_T1_557_SSID 012024_BEL_CBC_T1_557_SSID Healthy         1_3
012024_BEL_CBC_T1_559_MCAV 012024_BEL_CBC_T1_559_MCAV Healthy         1_24
012024_BEL_CBC_T1_561_OANN 012024_BEL_CBC_T1_561_OANN Healthy         1_25
012024_BEL_CBC_T1_563_PSTR 012024_BEL_CBC_T1_563_PSTR Healthy         1_12
012024_BEL_CBC_T1_565_PAST 012024_BEL_CBC_T1_565_PAST Bleached_Tissue 1_21
012024_BEL_CBC_T2_585_OFAV 012024_BEL_CBC_T2_585_OFAV Healthy         2_76
                           Date_ITS2  Condition Species Month_year Seq_run
012024_BEL_CBC_T1_557_SSID 7_7_2025   Healthy   SSID    Jan 2024   1
012024_BEL_CBC_T1_559_MCAV 12_15_2025 Healthy   MCAV    Jan 2024   2
012024_BEL_CBC_T1_561_OANN 1_21_2026  Healthy   OANN    Jan 2024   3
012024_BEL_CBC_T1_563_PSTR 7_7_2025   Healthy   PSTR    Jan 2024   1
012024_BEL_CBC_T1_565_PAST 2_17_2026  CLP       PAST    Jan 2024   4
012024_BEL_CBC_T2_585_OFAV 2_17_2026  Healthy   OFAV    Jan 2024   4
                           Transect sample_uid DateFormatted
012024_BEL_CBC_T1_557_SSID CBC30N   262771     2024-01-10
012024_BEL_CBC_T1_559_MCAV CBC30N   267721     2024-01-10
012024_BEL_CBC_T1_561_OANN CBC30N   267626     2024-01-10
012024_BEL_CBC_T1_563_PSTR CBC30N   262772     2024-01-10
012024_BEL_CBC_T1_565_PAST CBC30N   269104     2024-01-10
012024_BEL_CBC_T2_585_OFAV SR30N    269105     2024-01-12

In [74]:
otu_df <- as.data.frame(otu_veg)
#save sammple names as a column so tidy doesn't get rid of it during filtering
otu_df$SampleID <- rownames(otu_df)

### remove na from otu table

In [75]:
head(otu_df)

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2026464 2026486
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     ⋯ NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0     ⋯   0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0     ⋯   0       0
                           2023928 2027858 2029769 2028086 2028835 2027844
012024_BEL_CBC_T1_557_SSID NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_559_MCAV   0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN   0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR NaN     NaN     NaN     NaN     NaN     NaN
012024_BEL_CBC_T1_565_PAST   0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV   0       0       0       0       0       0
                           2027851 SampleID
012024_BEL_CBC_T1_557_SSID NaN     012024_BEL_CBC_T1_557_SSID
012024_BEL_CBC_T1_559_MCAV   0     012024_BEL_CBC_T1_559_MCAV
012024_BEL_CBC_T1_561_OANN   0     012024_BEL_CBC_T1_561_OANN
012024_BEL_CBC_T1_563_PSTR NaN     012024_BEL_CBC_T1_563_PSTR
012024_BEL_CBC_T1_565_PAST   0     012024_BEL_CBC_T1_565_PAST
012024_BEL_CBC_T2_585_OFAV   0     012024_BEL_CBC_T2_585_OFAV

In [76]:
# Replace all NA values with 0
otu_df[is.na(otu_df)] <- 0

In [77]:
head(otu_df)

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2026464 2026486
012024_BEL_CBC_T1_557_SSID 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       ⋯ 0       0
                           2023928 2027858 2029769 2028086 2028835 2027844
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           2027851 SampleID
012024_BEL_CBC_T1_557_SSID 0       012024_BEL_CBC_T1_557_SSID
012024_BEL_CBC_T1_559_MCAV 0       012024_BEL_CBC_T1_559_MCAV
012024_BEL_CBC_T1_561_OANN 0       012024_BEL_CBC_T1_561_OANN
012024_BEL_CBC_T1_563_PSTR 0       012024_BEL_CBC_T1_563_PSTR
012024_BEL_CBC_T1_565_PAST 0       012024_BEL_CBC_T1_565_PAST
012024_BEL_CBC_T2_585_OFAV 0       012024_BEL_CBC_T2_585_OFAV

## anova using vegan
-what is driving ITS2 clustering?

In [79]:
class(otu_veg)

[1] "matrix" "array"

In [83]:
otu_veg_df <- as.data.frame(otu_veg)
# Replace all NA values with 0
otu_veg_df[is.na(otu_veg_df)] <- 0

In [84]:
otu_veg_mat <- as.matrix(otu_veg_df)

In [85]:
head(otu_veg_mat)

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2027480 2026464
012024_BEL_CBC_T1_557_SSID 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       ⋯ 0       0
                           2026486 2023928 2027858 2029769 2028086 2028835
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           2027844 2027851
012024_BEL_CBC_T1_557_SSID 0       0
012024_BEL_CBC_T1_559_MCAV 0       0
012024_BEL_CBC_T1_561_OANN 0       0
012024_BEL_CBC_T1_563_PSTR 0       0
012024_BEL_CBC_T1_565_PAST 0       0
012024_BEL_CBC_T2_585_OFAV 0       0

In [113]:
# remove any samples with no OTU counts
otu<- otu_veg_mat[rowSums(otu_veg_mat) > 0, ]
sample_clean <- sample_clean[rowSums(otu) > 0, ]

In [116]:
class(otu)

[1] "matrix" "array"

### another way to run addonis more separated
# 5. Compute distance
dist <- vegdist(otu, method = "bray")

# 6. Run adonis2
adonis2(dist ~ Date_ITS2 + Month_year + Seq_run + Species + Health_status, data = sample_clean)

# hellinger distance to find 
otu_hel <- decostand(otu, method = "hellinger")

In [118]:
common_samples <- intersect(rownames(otu), rownames(sample_clean))

otu_clean <- otu[common_samples, ]
sample_clean <- sample_clean[common_samples, ]
all(rownames(otu_clean) == rownames(sample_clean))

[1] TRUE

In [119]:
#this one is species within transect with date as another variable
adonis2(vegdist(otu_clean, method = "bray") ~ Date_ITS2 + Month_year + Seq_run + Species + Health_status, data = sample_clean)

              Df  SumOfSqs    R2          F        Pr(>F)
Date_ITS2      25  22.3954303 0.096146027 1.978814 0.001
Month_year     11   5.4636227 0.023455929 1.097169 0.019
Seq_run         1   0.4976307 0.002136383 1.099241 0.024
Species         5  10.3058698 0.044244224 4.553027 0.001
Health_status   3   1.4169321 0.006083044 1.043310 0.269
Residual      426 192.8519327 0.827934394       NA    NA
Total         471 232.9314183 1.000000000       NA    NA

## anova without vegan, otu_merged

In [88]:
head(sample_clean)

                           SampleID                   Health_status   colony
012024_BEL_CBC_T1_557_SSID 012024_BEL_CBC_T1_557_SSID Healthy         1_3
012024_BEL_CBC_T1_559_MCAV 012024_BEL_CBC_T1_559_MCAV Healthy         1_24
012024_BEL_CBC_T1_561_OANN 012024_BEL_CBC_T1_561_OANN Healthy         1_25
012024_BEL_CBC_T1_563_PSTR 012024_BEL_CBC_T1_563_PSTR Healthy         1_12
012024_BEL_CBC_T1_565_PAST 012024_BEL_CBC_T1_565_PAST Bleached_Tissue 1_21
012024_BEL_CBC_T2_585_OFAV 012024_BEL_CBC_T2_585_OFAV Healthy         2_76
                           Date_ITS2  Condition Species Month_year Seq_run
012024_BEL_CBC_T1_557_SSID 7_7_2025   Healthy   SSID    Jan 2024   1
012024_BEL_CBC_T1_559_MCAV 12_15_2025 Healthy   MCAV    Jan 2024   2
012024_BEL_CBC_T1_561_OANN 1_21_2026  Healthy   OANN    Jan 2024   3
012024_BEL_CBC_T1_563_PSTR 7_7_2025   Healthy   PSTR    Jan 2024   1
012024_BEL_CBC_T1_565_PAST 2_17_2026  CLP       PAST    Jan 2024   4
012024_BEL_CBC_T2_585_OFAV 2_17_2026  Healthy   OFAV    Jan 2024   4
                           Transect sample_uid DateFormatted
012024_BEL_CBC_T1_557_SSID CBC30N   262771     2024-01-10
012024_BEL_CBC_T1_559_MCAV CBC30N   267721     2024-01-10
012024_BEL_CBC_T1_561_OANN CBC30N   267626     2024-01-10
012024_BEL_CBC_T1_563_PSTR CBC30N   262772     2024-01-10
012024_BEL_CBC_T1_565_PAST CBC30N   269104     2024-01-10
012024_BEL_CBC_T2_585_OFAV SR30N    269105     2024-01-12

In [89]:
head(otu_df)

                           1661676 1661811 1661272 1661422 1661525 1661677
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           1661737 1669273 1661179 1661509 ⋯ 2026464 2026486
012024_BEL_CBC_T1_557_SSID 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       ⋯ 0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       ⋯ 0       0
                           2023928 2027858 2029769 2028086 2028835 2027844
012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
                           2027851 SampleID
012024_BEL_CBC_T1_557_SSID 0       012024_BEL_CBC_T1_557_SSID
012024_BEL_CBC_T1_559_MCAV 0       012024_BEL_CBC_T1_559_MCAV
012024_BEL_CBC_T1_561_OANN 0       012024_BEL_CBC_T1_561_OANN
012024_BEL_CBC_T1_563_PSTR 0       012024_BEL_CBC_T1_563_PSTR
012024_BEL_CBC_T1_565_PAST 0       012024_BEL_CBC_T1_565_PAST
012024_BEL_CBC_T2_585_OFAV 0       012024_BEL_CBC_T2_585_OFAV

In [90]:
otu_merged <- merge(otu_df, sample_clean, by = "SampleID",
                    all = TRUE, sort = FALSE)
head(otu_merged)

  SampleID                   1661676 1661811 1661272 1661422 1661525 1661677
1 012024_BEL_CBC_T1_557_SSID 0       0       0       0       0       0
2 012024_BEL_CBC_T1_559_MCAV 0       0       0       0       0       0
3 012024_BEL_CBC_T1_561_OANN 0       0       0       0       0       0
4 012024_BEL_CBC_T1_563_PSTR 0       0       0       0       0       0
5 012024_BEL_CBC_T1_565_PAST 0       0       0       0       0       0
6 012024_BEL_CBC_T2_585_OFAV 0       0       0       0       0       0
  1661737 1669273 1661179 ⋯ Health_status   colony Date_ITS2  Condition Species
1 0       0       0       ⋯ Healthy         1_3    7_7_2025   Healthy   SSID
2 0       0       0       ⋯ Healthy         1_24   12_15_2025 Healthy   MCAV
3 0       0       0       ⋯ Healthy         1_25   1_21_2026  Healthy   OANN
4 0       0       0       ⋯ Healthy         1_12   7_7_2025   Healthy   PSTR
5 0       0       0       ⋯ Bleached_Tissue 1_21   2_17_2026  CLP       PAST
6 0       0       0       ⋯ Healthy         2_76   2_17_2026  Healthy   OFAV
  Month_year Seq_run Transect sample_uid DateFormatted
1 Jan 2024   1       CBC30N   262771     2024-01-10
2 Jan 2024   2       CBC30N   267721     2024-01-10
3 Jan 2024   3       CBC30N   267626     2024-01-10
4 Jan 2024   1       CBC30N   262772     2024-01-10
5 Jan 2024   4       CBC30N   269104     2024-01-10
6 Jan 2024   4       SR30N    269105     2024-01-12

In [ ]:
 # Compute the analysis of variance
otu.anov <- aov(nonchim ~ Date_16S + factor(Month_year) + Seq_run + Species + Health_status, data = otu_merged)
# Summary of the analysis
summary(otu.anov)

## anova with taxa

ANOVA works best when:

-Each row = one observation
-Variables = columns
-The response variable is a single column (not spread across many)

In [91]:
taxa <- read.csv(file="/work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/BEL_16S_ITS2/BEL_ITS2_outputs/symportal_taxa.csv")

In [96]:
otu_long <- otu_df %>%
  pivot_longer(
    cols = -SampleID,  
    names_to = "ITS2.type.profile.UID",
    values_to = "abundance"
  )

In [97]:
head(otu_long)

  SampleID                   ITS2.type.profile.UID abundance
1 012024_BEL_CBC_T1_557_SSID 1661676               0
2 012024_BEL_CBC_T1_557_SSID 1661811               0
3 012024_BEL_CBC_T1_557_SSID 1661272               0
4 012024_BEL_CBC_T1_557_SSID 1661422               0
5 012024_BEL_CBC_T1_557_SSID 1661525               0
6 012024_BEL_CBC_T1_557_SSID 1661677               0

In [101]:
str(otu_long$ITS2.type.profile.UID)
str(taxa$ITS2.type.profile.UID)

#convert taxaITS2.type.profile to chr
taxa$ITS2.type.profile.UID <- as.character(taxa$ITS2.type.profile.UID)

 chr [1:198075] "1661676" "1661811" "1661272" "1661422" "1661525" "1661677" ...
 int [1:417] 1661676 1661811 1661272 1661422 1661525 1661677 1661737 1669273 1661179 1661509 ...

In [102]:
otu_taxa <- otu_long %>%
  left_join(taxa, by = "ITS2.type.profile.UID")

In [103]:
head(otu_taxa)

  SampleID                   ITS2.type.profile.UID abundance X Clade
1 012024_BEL_CBC_T1_557_SSID 1661676               0         1 A
2 012024_BEL_CBC_T1_557_SSID 1661811               0         2 A
3 012024_BEL_CBC_T1_557_SSID 1661272               0         3 A
4 012024_BEL_CBC_T1_557_SSID 1661422               0         4 A
5 012024_BEL_CBC_T1_557_SSID 1661525               0         5 A
6 012024_BEL_CBC_T1_557_SSID 1661677               0         6 A
  Majority.ITS2.sequence
1 A3/A4/A13
2 A3
3 A3/A4
4 A3bb/A3bt
5 A3/A13
6 A4/A3/A4a
  Associated.species
1 Symbiodinium natans,Symbiodinium tridacnidorum,Symbiodinium necroappetens
2 Symbiodinium natans,Symbiodinium tridacnidorum
3 Symbiodinium natans,Symbiodinium tridacnidorum
4 None
5 Symbiodinium natans,Symbiodinium tridacnidorum,Symbiodinium necroappetens
6 Symbiodinium natans,Symbiodinium tridacnidorum
  ITS2.profile.abundance.local ITS2.profile.abundance.DB ITS2.type.profile
1 21                            26                       A3/A4/A13-A4a
2 11                           230                       A3
3 10                            22                       A3/A4/A4a
4  9                           322                       A3bb/A3bt
5  8                            28                       A3/A13
6  8                             8                       A4/A3/A4a-A4d
  Sequence.accession...SymPortal.UID
1 22385/29206/8181-40166
2 22385
3 22385/29206-40166
4
5
6 29206/22385/40166-29900
  Average.defining.sequence.proportions.and..stdev.
1 0.634[0.211]/0.150[0.114]-0.111[0.095]/0.105[0.186]
2 1.000[0.000]
3 0.657[0.295]/0.198[0.147]-0.144[0.151]
4 0.515[0.062]/0.485[0.062]
5 0.627[0.220]/0.373[0.220]
6 0.330[0.130]/0.292[0.241]/0.288[0.136]-0.089[0.061]

In [104]:
# join sample data
full_data <- otu_taxa %>%
  left_join(sample_clean, by = "SampleID")

In [106]:
taxa.anov <- aov(abundance ~ Date_ITS2 + factor(Month_year) + Seq_run + Species + Health_status, data = full_data)
summary(taxa.anov)

                       Df    Sum Sq   Mean Sq F value Pr(>F)
Date_ITS2              25 1.393e+09 5.574e+07   0.026  1.000
factor(Month_year)     11 3.123e+08 2.839e+07   0.013  1.000
Seq_run                 1 8.138e+06 8.138e+06   0.004  0.951
Species                 5 3.863e+07 7.726e+06   0.004  1.000
Health_status           3 2.276e+07 7.588e+06   0.004  1.000
Residuals          198029 4.268e+14 2.155e+09

In [107]:
full_data <- full_data %>%
  mutate(presence = abundance > 0)

glm_model <- glm(presence ~ Date_ITS2 + factor(Month_year) + Seq_run + Species + Health_status,
                 data = full_data,
                 family = binomial)
summary(glm_model)

Call:
glm(formula = presence ~ Date_ITS2 + factor(Month_year) + Seq_run +
    Species + Health_status, family = binomial, data = full_data)

Deviance Residuals:
    Min       1Q   Median       3Q      Max
-0.1489  -0.1250  -0.1185  -0.1123   3.3609

Coefficients:
                             Estimate Std. Error z value Pr(>|z|)
(Intercept)                  -7.39876    2.50669  -2.952  0.00316 **
Date_ITS21_20_2026            0.01963    0.16536   0.119  0.90553
Date_ITS21_21_2026            0.06955    0.16073   0.433  0.66525
Date_ITS212_10_2025           0.86941    0.85758   1.014  0.31068
Date_ITS212_15_2025           0.80206    0.86136   0.931  0.35177
Date_ITS212_16_2025           0.85079    0.85510   0.995  0.31976
Date_ITS212_17_2025           0.76051    0.85938   0.885  0.37618
Date_ITS212_18_2025           0.64207    0.86112   0.746  0.45590
Date_ITS212_19_2025           0.85242    0.85864   0.993  0.32083
Date_ITS212_22_2025           0.22349    0.60577   0.369  0.71217
Date_ITS22_12_2026           -0.41067    0.84953  -0.483  0.62881
Date_ITS22_17_2026           -0.49962    0.84814  -0.589  0.55581
Date_ITS22_23_2026           -0.52031    0.85194  -0.611  0.54138
Date_ITS23_12_2026           -1.09094    1.67746  -0.650  0.51546
Date_ITS23_13_2026           -1.18114    1.67762  -0.704  0.48140
Date_ITS23_16_2026           -1.29081    1.67891  -0.769  0.44199
Date_ITS23_17_2026           -0.80745    1.70555  -0.473  0.63591
Date_ITS26_26_2025            1.83813    1.68593   1.090  0.27559
Date_ITS26_27_2025            1.55394    1.69196   0.918  0.35839
Date_ITS26_30_2025            1.97087    1.68162   1.172  0.24119
Date_ITS27_10_2025            1.68429    1.68408   1.000  0.31725
Date_ITS27_11_2025            1.70580    1.68762   1.011  0.31213
Date_ITS27_2_2025             2.01780    1.68544   1.197  0.23123
Date_ITS27_3_2025             1.77873    1.67881   1.060  0.28936
Date_ITS27_7_2025             1.59364    1.68671   0.945  0.34475
Date_ITS27_9_2025             1.77637    1.68259   1.056  0.29109
factor(Month_year)Oct 2019   -0.03965    0.23712  -0.167  0.86720
factor(Month_year)May 2022    0.07326    0.13673   0.536  0.59209
factor(Month_year)Dec 2022    0.05038    0.13096   0.385  0.70043
factor(Month_year)Sep 2023    0.04205    0.14096   0.298  0.76547
factor(Month_year)Nov 2023    0.09715    0.16440   0.591  0.55458
factor(Month_year)Dec 2023    0.14879    0.15517   0.959  0.33764
factor(Month_year)Jan 2024    0.10405    0.15607   0.667  0.50496
factor(Month_year)Feb 2024    0.06364    0.14816   0.430  0.66755
factor(Month_year)Apr 2024    0.14769    0.14095   1.048  0.29475
factor(Month_year)Jun 2024    0.10611    0.14698   0.722  0.47034
factor(Month_year)Aug 2024    0.12568    0.14792   0.850  0.39551
Seq_run                       0.74448    0.83522   0.891  0.37274
SpeciesOANN                  -0.13118    0.14849  -0.883  0.37698
SpeciesOFAV                  -0.06043    0.09371  -0.645  0.51902
SpeciesPAST                  -0.10726    0.08161  -1.314  0.18874
SpeciesPSTR                   0.03791    0.09078   0.418  0.67621
SpeciesSSID                  -0.01390    0.08651  -0.161  0.87236
Health_statusDiseased_Margin -0.02401    0.15864  -0.151  0.87972
Health_statusDiseased_Tissue  0.02429    0.13136   0.185  0.85333
Health_statusHealthy         -0.02905    0.09862  -0.295  0.76834
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 16735  on 198074  degrees of freedom
Residual deviance: 16697  on 198029  degrees of freedom
AIC: 16789

Number of Fisher Scoring iterations: 8

#### ways to test what drives ITS2 composition
- PERMANOVA (most common)
- multivariate GLMs (mvabund)
- compositional methods

In [ ]:
 # Compute the analysis of variance
taxa.anov <- aov(nonchim ~ Date_ITS2 + factor(Month_year) + Seq_run + Species + Health_status, data = otu_merged)
# Summary of the analysis
summary(taxa.anov)

## nmds plots