In [3]:
require(dplyr)
require(tidyverse)
require(data.table)

# use colony column to reference each unique colony, 
- new columns MonthYear, species, tag num
## new health status column including CLP and CLB for each tag num at each MonthYear

In [5]:
#load datasheets
meta=fread("/home/caroline_desouza_uml_edu/3_randomized_nonimmune_PCR.csv", header=TRUE)
colony=read.csv(file="/home/caroline_desouza_uml_edu/CBC_ColonyData.csv", header=TRUE)

In [6]:
head(meta)
head(colony)

  V1 Tubelabel_species           Health_Status Date_Extracted Raw_ng_ul
1 NA 052022_BEL_CBC_T1_2_SSID    Healthy       12_2_2024      7.73
2 NA 092023_BEL_CBC_T1_175_PAST  Healthy       1_15_2025      2.3
3 NA 022024_BEL_CBC_T3_851_PSTR  Healthy       11_26_2024     64.2
4 NA 082024_BEL_CBC_T4_1609_OFAV Healthy       1_15_2025      61.2
5 NA 122023_BEL_CBC_T3_526_SSID  Healthy       11_19_2024     16.4
6 NA 112023_BEL_CBC_T4_399_MCAV  Healthy       11_15_2024     13.9
  Extraction_physical_location           Date_Enriched Microbe_Location colony
1 UML_NARWHAL_R2_B14, UML_NARWHAL_R2_B33                                1_3
2 UML_NARWHAL_R2_B15                                                    1_13
3 UML_NARWHAL_R2_B13                                                    3_70
4 UML_NARWHAL_R2_B15                                                    4_78
5 UML_NARWHAL_R2_B13                                                    3_5
6 UML_NARWHAL_R2_B12                                                    4_76
  Date_16S  Date_ITS2 16S_double_band
1 1_22_2025 6_26_2025
2 1_22_2025 6_26_2025 y
3 1_23_2025 6_26_2025
4 1_23_2025 6_26_2025 y
5 1_23_2025 6_26_2025
6 1_23_2025 6_26_2025

  X Date_InitialTag Transect TransectNum OldTagNum NewTagNum Species Meter
1 1 6/21/19         CBC30N   1           349       1         SSID    1.5
2 2 6/21/19         CBC30N   1           334       2         PAST    1.4
3 3 6/21/19         CBC30N   1           346       3         SSID    6.3
4 4 10/15/19        CBC30N   1           407       4         PSTR    6.5
5 5 6/24/19         CBC30N   1           394       5         SSID    4.3
6 6 10/15/19        CBC30N   1           413       6         PSTR    8.3
  Meters_90 Direction ⋯ X082024_Percentage
1 0.50      right     ⋯
2 0.10      left      ⋯
3 0.80      right     ⋯
4 0.50      right     ⋯
5 1.20      left      ⋯
6 1.75      left      ⋯
  Notes_082024
1
2 sample lower colony (original colony); inc old mort; too small for immune
3 some discoloration
4
5
6
  X122024_Condition X122024_Percentage Notes_122024  X062025_Condition
1 Not_visited                          Diseased      Diseased
2                                                    Healthy
3 DC                10%                30% mortality Diseased
4 Dead                                 Dead          Dead
5 DC                10%                80% mortality Diseased
6 Dead                                               Dead
  X062025_Percentage Notes_062025 immune_y.n checked_colonies
1                                 n          x
2                                 y          x
3                                 y          x
4                                 n          x
5                                 n          x
6                                 n          x

In [7]:
# no longer isloate immune samples
## colony_immune=colony[colony$immune_y.n=="y",]

#make new column colony in colony data to match meta
colony$colony <- c(paste0(colony$TransectNum, "_", colony_immune$NewTagNum))

In [51]:
head(colony_immune)

   X  Date_InitialTag Transect TransectNum OldTagNum NewTagNum Species Meter
2   2 6/21/19         CBC30N   1           334       2         PAST     1.4
3   3 6/21/19         CBC30N   1           346       3         SSID     6.3
12 12 10/15/19        CBC30N   1           418       12        PSTR    14.7
13 13 6/24/19         CBC30N   1           395       13        PAST    15.8
20 21 6/24/19         CBC30N   1           397       21        PAST     4.0
23 18 6/24/19         CBC30N   1           380       24        MCAV     9.9
   Meters_90 Direction ⋯
2  0.1       left      ⋯
3  0.8       right     ⋯
12 1.0       left      ⋯
13 1.4       right     ⋯
20 4.0       right     ⋯
23 3.0       left      ⋯
   Notes_082024
2  sample lower colony (original colony); inc old mort; too small for immune
3  some discoloration
12
13
20
23 pale spot from sponge competition (not on part sampled)
   X122024_Condition X122024_Percentage Notes_122024  X062025_Condition
2                                                     Healthy
3  DC                10%                30% mortality Diseased
12 Healthy                              5% mortality  Healthy
13 Dead                                 5% mortality  Dead
20 Not_visited                                        Dead
23 Healthy                              95% mortality Healthy
   X062025_Percentage Notes_062025 immune_y.n checked_colonies colony
2                                  y          x                1_2
3                                  y          x                1_3
12                                 y          x                1_12
13                                 y          x                1_13
20                                 y          x                1_21
23                                 y          x                1_24

In [52]:
colnames(colony_immune)

 [1] "X"                        "Date_InitialTag"
 [3] "Transect"                 "TransectNum"
 [5] "OldTagNum"                "NewTagNum"
 [7] "Species"                  "Meter"
 [9] "Meters_90"                "Direction"
[11] "Size_Class"               "MaxDiameter"
[13] "Height"                   "Date_DocumentedDisease"
[15] "Date_DocumentedMortality" "Notes_062019"
[17] "X062019_Condition"        "X062019_Percentage"
[19] "Notes_052022"             "X052022_Condition"
[21] "X052022_Percentage"       "Notes_122022"
[23] "X122022_Condition"        "X122022_Percentage"
[25] "Notes_092023"             "X092023_Condition"
[27] "X092023_Percentage"       "Notes_112023"
[29] "X112023_Condition"        "X112023_Percentage"
[31] "Notes_122023"             "X122023_Condition"
[33] "X122023_Percentage"       "Notes_012024"
[35] "X012024_Condition"        "X012024_Percentage"
[37] "Notes_022024"             "X022024_Condition"
[39] "X022024_Percentage"       "Notes_042024"
[41] "X042024_Condition"        "X042024_Percentage"
[43] "X062024_Condition"        "X062024_Percentage"
[45] "Notes_062024"             "X082024_Condition"
[47] "X082024_Percentage"       "Notes_082024"
[49] "X122024_Condition"        "X122024_Percentage"
[51] "Notes_122024"             "X062025_Condition"
[53] "X062025_Percentage"       "Notes_062025"
[55] "immune_y.n"               "checked_colonies"
[57] "colony"

In [53]:
#cclean to just include Condition columns and colony'
colony_clean=colony_immune[c('colony', 'X062019_Condition', 'X052022_Condition', 'X122022_Condition', 'X092023_Condition', 'X112023_Condition', 'X122023_Condition','X012024_Condition','X022024_Condition', 'X042024_Condition', 'X062024_Condition', 'X082024_Condition')]
head(colony_clean)

   colony X062019_Condition X052022_Condition X122022_Condition
2  1_2    Healthy           Healthy           Healthy
3  1_3    Healthy           Diseased          Healthy
12 1_12   Healthy           Healthy           Healthy
13 1_13   Healthy           Healthy           Healthy
20 1_21   Healthy           Healthy           Healthy
23 1_24   Healthy           Healthy           Healthy
   X092023_Condition X112023_Condition X122023_Condition X012024_Condition
2  CLP,CLB           CLB               CLB               CLP,CLB
3  Diseased          CLP               Healthy           Healthy
12 Healthy           CLP               Healthy           Healthy
13 Healthy           CLP               Dead              Dead
20 CLP               CLP               CLB,CLP           CLP
23 CLP               CLP               Healthy           Healthy
   X022024_Condition X042024_Condition X062024_Condition X082024_Condition
2  Healthy           Not_Visited       Healthy           Healthy
3  Diseased          Diseased          Diseased          Diseased
12 Healthy           Healthy           Healthy           Healthy
13 Dead              Dead              Dead              Dead
20 Dead              Dead              Dead              Dead
23 Healthy           Healthy           Healthy           Healthy

In [54]:
colnames(colony_clean)

 [1] "colony"            "X062019_Condition" "X052022_Condition"
 [4] "X122022_Condition" "X092023_Condition" "X112023_Condition"
 [7] "X122023_Condition" "X012024_Condition" "X022024_Condition"
[10] "X042024_Condition" "X062024_Condition" "X082024_Condition"

In [55]:
#rename condition columns to corresponding Monthyear
colony_clean <- colony_clean %>%
  rename_with(
    .cols = matches("^X\\d{6}_Condition$"),
    .fn = ~ str_extract(., "\\d{6}")
  )

In [56]:
head(colony_clean)

   colony 062019  052022   122022  092023   112023 122023  012024  022024
2  1_2    Healthy Healthy  Healthy CLP,CLB  CLB    CLB     CLP,CLB Healthy
3  1_3    Healthy Diseased Healthy Diseased CLP    Healthy Healthy Diseased
12 1_12   Healthy Healthy  Healthy Healthy  CLP    Healthy Healthy Healthy
13 1_13   Healthy Healthy  Healthy Healthy  CLP    Dead    Dead    Dead
20 1_21   Healthy Healthy  Healthy CLP      CLP    CLB,CLP CLP     Dead
23 1_24   Healthy Healthy  Healthy CLP      CLP    Healthy Healthy Healthy
   042024      062024   082024
2  Not_Visited Healthy  Healthy
3  Diseased    Diseased Diseased
12 Healthy     Healthy  Healthy
13 Dead        Dead     Dead
20 Dead        Dead     Dead
23 Healthy     Healthy  Healthy

In [57]:
#pivot longer colony to join all date columns into one monthyear column
colony_long <- colony_clean %>%
  pivot_longer(
    cols = matches("^\\d{6}$"),      # after renaming
    names_to = "MonthYear",
    values_to = "Condition"
  )
head(colony_long)

  colony MonthYear Condition
1 1_2    062019    Healthy
2 1_2    052022    Healthy
3 1_2    122022    Healthy
4 1_2    092023    CLP,CLB
5 1_2    112023    CLB
6 1_2    122023    CLB

In [58]:
#make monthyear column in meta from tubelabel_species
#cleaning samdt
meta <- meta[meta$Date_ITS2 != 'NA', ]
# Create a new data frame with the species, date, and transect columns
# Example samdt (make sure your data is a data.table)
setDT(meta)
# Split Tubelabel_species by "_" and assign new columns
meta[, c("date_sampled") := {
  parts <- strsplit(Tubelabel_species, "_")
  list(
    sapply(parts, `[`, 1)  # date is first element
  )
}]

#changing format of date_sampled to be Jan 2024
meta$date_sampled <- as.factor(meta$date_sampled)
# Convert to Date format 
meta$DateFormatted <- as.Date(paste0(meta$date_sampled, "01"), format = "%m%Y%d")
# now will have a new column that has Month Year instead of date_sampled
meta$MonthYear <- format(meta$DateFormatted, "%b %Y")
meta$MonthYear <- factor(meta$MonthYear, levels = unique(meta$MonthYear))

In [59]:
meta_clean <- meta[, c("V1", "Date_Extracted", "Raw_ng_ul", "Extraction_physical_location", "Date_Enriched","Microbe_Location", "Date_16S", "16S double band", "date_sampled", "transect", "species", "V13", "DateFormatted") := NULL]

Warning message in `[.data.table`(meta, , `:=`(c("V1", "Date_Extracted", "Raw_ng_ul", :
“Tried to assign NULL to column 'transect', but this column does not exist to remove”
Warning message in `[.data.table`(meta, , `:=`(c("V1", "Date_Extracted", "Raw_ng_ul", :
“Tried to assign NULL to column 'species', but this column does not exist to remove”

In [60]:
head(meta_clean)
head(colony_long)

  Tubelabel_species           Health_Status colony Date_ITS2 MonthYear
1 052022_BEL_CBC_T1_2_SSID    Healthy       1_3    6_26_2025 May 2022
2 092023_BEL_CBC_T1_175_PAST  Healthy       1_13   6_26_2025 Sep 2023
3 022024_BEL_CBC_T3_851_PSTR  Healthy       3_70   6_26_2025 Feb 2024
4 082024_BEL_CBC_T4_1609_OFAV Healthy       4_78   6_26_2025 Aug 2024
5 122023_BEL_CBC_T3_526_SSID  Healthy       3_5    6_26_2025 Dec 2023
6 112023_BEL_CBC_T4_399_MCAV  Healthy       4_76   6_26_2025 Nov 2023

  colony MonthYear Condition
1 1_2    062019    Healthy
2 1_2    052022    Healthy
3 1_2    122022    Healthy
4 1_2    092023    CLP,CLB
5 1_2    112023    CLB
6 1_2    122023    CLB

In [61]:
#changing colony_long to be Jan 2024
colony_long$date_sampled <- as.factor(colony_long$MonthYear)
# Convert to Date format 
colony_long$DateFormatted <- as.Date(paste0(colony_long$date_sampled, "01"), format = "%m%Y%d")
# now will have a new column that has Month Year instead of date_sampled
colony_long$MonthYear <- format(colony_long$DateFormatted, "%b %Y")
colony_long$MonthYear <- factor(colony_long$MonthYear, levels = unique(colony_long$MonthYear))

#remove columns
colony_long$date_sampled <- NULL
colony_long$DateFormatted <- NULL

In [62]:
head(colony_long)

  colony MonthYear Condition
1 1_2    Jun 2019  Healthy
2 1_2    May 2022  Healthy
3 1_2    Dec 2022  Healthy
4 1_2    Sep 2023  CLP,CLB
5 1_2    Nov 2023  CLB
6 1_2    Dec 2023  CLB

In [63]:
class(colony_long)
class(meta)

[1] "tbl_df"     "tbl"        "data.frame"

[1] "data.table" "data.frame"

In [64]:
#merge new colony_long and meta
meta_update <- merge(meta, colony_long,
                     by = c("MonthYear", "colony"),
                     all = FALSE)

In [65]:
meta_update

    MonthYear colony Tubelabel_species           Health_Status   Date_ITS2
1   May 2022  1_2    052022_BEL_CBC_T1_1_PAST    Healthy         12_18_2025
2   May 2022  1_3    052022_BEL_CBC_T1_2_SSID    Healthy         6_26_2025
3   May 2022  2_55   052022_BEL_CBC_T2_12_MCAV   Healthy         12_15_2025
4   May 2022  2_63   052022_BEL_CBC_T2_9_PAST    Healthy         6_30_2025
5   May 2022  2_68   052022_BEL_CBC_T2_5_PAST    Healthy         12_16_2025
6   May 2022  2_72   052022_BEL_CBC_T2_3_SSID    Healthy         12_15_2025
7   May 2022  2_73   052022_BEL_CBC_T2_1_SSID    Healthy         7_7_2025
8   May 2022  2_79   052022_BEL_CBC_T2_71_OFAV   Healthy         6_27_2025
9   May 2022  3_10   052022_BEL_CBC_T3_8_PAST    Healthy         6_27_2025
10  May 2022  3_14   052022_BEL_CBC_T3_13_MCAV   Healthy         7_11_2025
11  May 2022  3_2    052022_BEL_CBC_T3_1_MCAV    Healthy         12_19_2025
12  May 2022  3_20   052022_BEL_CBC_T3_15_PSTR   Healthy         12_22_2025
13  May 2022  3_21   052022_BEL_CBC_T3_19_MCAV   Healthy         7_11_2025
14  May 2022  3_38   052022_BEL_CBC_T3_66_OFAV   Healthy         7_9_2025
15  May 2022  3_6    052022_BEL_CBC_T3_11_PAST   Healthy         6_27_2025
16  Sep 2023  1_13   092023_BEL_CBC_T1_175_PAST  Healthy         6_26_2025
17  Sep 2023  1_2    092023_BEL_CBC_T1_171_PAST  Healthy         7_3_2025
18  Sep 2023  1_24   092023_BEL_CBC_T1_174_MCAV  Healthy         12_22_2025
19  Sep 2023  1_3    092023_BEL_CBC_T1_173_SSID  Healthy         12_18_2025
20  Sep 2023  2_55   092023_BEL_CBC_T2_183_MCAV  Healthy         12_10_2025
21  Sep 2023  2_60   092023_BEL_CBC_T2_184_MCAV  Healthy         7_2_2025
22  Sep 2023  2_63   092023_BEL_CBC_T2_181_PAST  Healthy         7_7_2025
23  Sep 2023  2_68   092023_BEL_CBC_T2_175_PAST  Healthy         12_17_2025
24  Sep 2023  2_72   092023_BEL_CBC_T2_174_SSID  Healthy         7_3_2025
25  Sep 2023  2_99   092023_BEL_CBC_T2_179_SSID  Healthy         12_16_2025
26  Sep 2023  3_14   092023_BEL_CBC_T3_175_MCAV  Healthy         12_18_2025
27  Sep 2023  3_21   092023_BEL_CBC_T3_182_MCAV  Healthy         12_19_2025
28  Sep 2023  3_38   092023_BEL_CBC_T3_174_OFAV  Healthy         12_10_2025
29  Sep 2023  3_39   092023_BEL_CBC_T3_171_OFAV  Healthy         7_9_2025
30  Sep 2023  3_5    092023_BEL_CBC_T3_177_SSID  Healthy         12_19_2025
⋮   ⋮         ⋮      ⋮                           ⋮               ⋮
161 Jun 2024  1_12   062024_BEL_CBC_T1_1350_PSTR Healthy         12_16_2025
162 Jun 2024  1_24   062024_BEL_CBC_T1_1353_MCAV Healthy         7_10_2025
163 Jun 2024  1_25   062024_BEL_CBC_T1_1347_OANN Healthy         7_7_2025
164 Jun 2024  2_69   062024_BEL_CBC_T2_1396_MCAV Healthy         7_3_2025
165 Jun 2024  2_73   062024_BEL_CBC_T2_1375_SSID Healthy         7_2_2025
166 Jun 2024  3_10   062024_BEL_CBC_T3_1424_PAST Healthy         12_18_2025
167 Jun 2024  3_14   062024_BEL_CBC_T3_1427_MCAV Healthy         12_19_2025
168 Jun 2024  3_2    062024_BEL_CBC_T3_1415_MCAV Diseased_Tissue 7_3_2025
169 Jun 2024  3_21   062024_BEL_CBC_T3_1436_MCAV Healthy         12_16_2025
170 Jun 2024  3_39   062024_BEL_CBC_T3_1442_OFAV Healthy         7_2_2025
171 Jun 2024  3_66   062024_BEL_CBC_T3_1439_OFAV Healthy         7_3_2025
172 Jun 2024  3_70   062024_BEL_CBC_T3_1433_PSTR Healthy         7_11_2025
173 Jun 2024  4_79   062024_BEL_CBC_T4_1473_PSTR Healthy         12_19_2025
174 Jan 2024  1_12   012024_BEL_CBC_T1_563_PSTR  Healthy         7_7_2025
175 Jan 2024  1_24   012024_BEL_CBC_T1_559_MCAV  Healthy         12_15_2025
176 Jan 2024  1_3    012024_BEL_CBC_T1_557_SSID  Healthy         7_7_2025
177 Jan 2024  2_60   012024_BEL_CBC_T2_599_MCAV  Healthy         12_19_2025
178 Jan 2024  2_63   012024_BEL_CBC_T2_595_PAST  Healthy         12_19_2025
179 Jan 2024  2_68   012024_BEL_CBC_T2_591_PAST  Healthy         12_15_2025
180 Jan 2024  2_79   012024_BEL_CBC_T2_601_OFAV  Healthy         7_7_2025
181 Jan 2024  2_99   012024_BEL_CBC_T2_605_SSID  Healthy         7_10_2025
182 Jan 2024  3_2    012024_BEL_CBC_T3_633_MCAV  Healthy         7_7_2025
183 Jan 2024  3_21   012024_BEL_CBC_T3_631_MCAV  Healthy         7_7_2025
184 Jan 2024  3_34   012024_BEL_CBC_T3_627_PAST  Healthy         7_10_2025
185 Jan 2024  3_5    012024_BEL_CBC_T3_637_SSID  Healthy         7_7_2025
186 Jan 2024  3_66   012024_BEL_CBC_T3_639_OFAV  Healthy         12_22_2025
187 Jan 2024  4_30   012024_BEL_CBC_T4_669_MCAV  Healthy         12_15_2025
188 Jan 2024  4_76   012024_BEL_CBC_T4_665_MCAV  Healthy         12_15_2025
189 Jan 2024  4_79   012024_BEL_CBC_T4_663_PSTR  Healthy         7_10_2025
190 Jan 2024  4_98   012024_BEL_CBC_T4_661_PSTR  Healthy         7_9_2025
    Condition
1   Healthy
2   Diseased
3   Healthy
4   Healthy
5   Healthy
6   CLB
7   Healthy
8   Healthy
9   Healthy
10  Healthy
11  Healthy
12  Healthy
13  Healthy
14  Healthy
15  Healthy
16  Healthy
17  CLP,CLB
18  CLP
19  Diseased
20  CLP
21  CLP,CLB
22  Healthy
23  Healthy
24  CLB
25  CLP
26  Healthy
27  Healthy
28  Healthy
29  Healthy
30  Healthy
⋮   ⋮
161 Healthy
162 Healthy
163 Healthy
164 Healthy
165 DC
166 Healthy
167 Healthy
168 Diseased_Other
169 Healthy
170 Healthy
171 Healthy
172 Healthy
173 Healthy
174 Healthy
175 Healthy
176 Healthy
177 Healthy
178 Healthy
179 Healthy
180 Healthy
181 CLB
182 Diseased_Other, CLP
183 Healthy
184 Healthy
185 Healthy
186 Healthy
187 Healthy
188 Healthy
189 Healthy
190 CLB

In [66]:
write.csv(meta_update, file="/home/caroline_desouza_uml_edu/run3_pcr_meta.csv")

# use updated meta sheet to add date_its2 and health status to symportal sheet

In [11]:
symportal <- read.csv("/home/caroline_desouza_uml_edu/run3_SymPortal_datasheet.csv",
                      header = FALSE, stringsAsFactors = FALSE)
pcr=read.csv(file="/home/caroline_desouza_uml_edu/meta_PCR.csv", header=TRUE, row.names=1)

In [12]:
head(symportal)
head(pcr)

  V1                          V2                  V3
1 sample_name                 fastq_fwd_file_name fastq_rev_file_name
2 012024_BEL_CBC_T3_639_OFAV
3 122023_BEL_CBC_T2_520_PAST
4 052022_BEL_CBC_T2_10_MCAV
5 042024_BEL_CBC_T2_1035_SSID
6 052022_BEL_CBC_T3_65_OFAV
  V4          V5          V6            V7           V8
1 sample_type host_phylum host_class    host_order   host_family
2 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Poritidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
  V9           V10          V11                 V12
1 host_genus   host_species collection_latitude collection_longitude
2 Orbicella    faveolata    16.8088             -88.08615
3 Porites      asteroides   16.77998            -88.07654
4 Montastrea   cavernosa    16.77998            -88.07654
5 Siderastrea  sidera       16.77998            -88.07654
6 Orbicella    faveolata    16.8088             -88.08615
  V13             V14
1 collection_date collection_depth
2 20240110        6
3 20231215        8
4 20220524        8
5 20240426        8
6 20220520        6

  X   Tubelabel_species           Date_Extracted Raw_ng_ul Date_Enriched
1 104 052022_BEL_CBC_T1_2_SSID    12_2_2024      7.73
3 232 092023_BEL_CBC_T1_175_PAST  1_15_2025      2.3
4  59 022024_BEL_CBC_T3_851_PSTR  11_26_2024     64.2
5 225 082024_BEL_CBC_T4_1609_OFAV 1_15_2025      61.2
8 358 122023_BEL_CBC_T3_526_SSID  11_19_2024     16.4
7 298 112023_BEL_CBC_T4_399_MCAV  11_15_2024     13.9
  Microbe_Location Month_year colony CollectionDate Species Health_status
1                   52022     1_3    5/21/22        SSID    Diseased_Tissue
3                   92023     1_13   9/25/23        PAST    Healthy
4                   22024     3_70   2/24/24        PSTR    Healthy
5                   82024     4_78   8/22/24        OFAV    Healthy
8                  122023     3_5    12/16/23       SSID    Healthy
7                  112023     4_76   11/13/23       MCAV    Bleached_Tissue
  Sample_physical_location Extraction_physical_location           immune_y.n
1 UML_NARWHAL_R1_B3        UML_NARWHAL_R2_B14, UML_NARWHAL_R2_B33 y
3 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12                     y
4 UML_NARWHAL_R5_B23       UML_NARWHAL_R2_B13                     y
5 UML_NARWHAL_R5_B27       UML_NARWHAL_R2_B15                     y
8 UML_NARWHAL_R5_B19       UML_NARWHAL_R2_B13                     y
7 UML_NARWHAL_R5_B19       UML_NARWHAL_R2_B12                     y
  Condition Date_16S  Date_ITS2 Run_num
1 Diseased  1_22_2025 6_26_2025 1
3 Healthy   1_22_2025 6_26_2025 1
4 Healthy   1_23_2025 6_26_2025 1
5 Healthy   1_23_2025 6_26_2025 1
8 Healthy   1_23_2025 6_26_2025 1
7 CLP       1_23_2025 6_26_2025 1

In [13]:
# Make row 2 the header
colnames(symportal) <- symportal[1, ]
# Delete rows 1 and 2
symportal <- symportal[-c(1), ]

In [14]:
head(symportal)

  sample_name                 fastq_fwd_file_name fastq_rev_file_name
2 012024_BEL_CBC_T3_639_OFAV
3 122023_BEL_CBC_T2_520_PAST
4 052022_BEL_CBC_T2_10_MCAV
5 042024_BEL_CBC_T2_1035_SSID
6 052022_BEL_CBC_T3_65_OFAV
7 092023_BEL_CBC_T4_93_PSTR
  sample_type host_phylum host_class    host_order   host_family
2 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Poritidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
7 coral_field Cnidaria    Hexacorallia  Scleractinia Faviidae
  host_genus     host_species collection_latitude collection_longitude
2 Orbicella      faveolata    16.8088             -88.08615
3 Porites        asteroides   16.77998            -88.07654
4 Montastrea     cavernosa    16.77998            -88.07654
5 Siderastrea    sidera       16.77998            -88.07654
6 Orbicella      faveolata    16.8088             -88.08615
7 Pseudodiploria strigosa     16.77976            -88.10117
  collection_date collection_depth
2 20240110        6
3 20231215        8
4 20220524        8
5 20240426        8
6 20220520        6
7 20230926        6

In [15]:
symportal$sample_name <- gsub("-", "_", symportal$sample_name)
head(symportal)

  sample_name                 fastq_fwd_file_name fastq_rev_file_name
2 012024_BEL_CBC_T3_639_OFAV
3 122023_BEL_CBC_T2_520_PAST
4 052022_BEL_CBC_T2_10_MCAV
5 042024_BEL_CBC_T2_1035_SSID
6 052022_BEL_CBC_T3_65_OFAV
7 092023_BEL_CBC_T4_93_PSTR
  sample_type host_phylum host_class    host_order   host_family
2 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Poritidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
7 coral_field Cnidaria    Hexacorallia  Scleractinia Faviidae
  host_genus     host_species collection_latitude collection_longitude
2 Orbicella      faveolata    16.8088             -88.08615
3 Porites        asteroides   16.77998            -88.07654
4 Montastrea     cavernosa    16.77998            -88.07654
5 Siderastrea    sidera       16.77998            -88.07654
6 Orbicella      faveolata    16.8088             -88.08615
7 Pseudodiploria strigosa     16.77976            -88.10117
  collection_date collection_depth
2 20240110        6
3 20231215        8
4 20220524        8
5 20240426        8
6 20220520        6
7 20230926        6

In [16]:
#get rid of empty rows
symportal <- symportal[!is.na(symportal$sample_name), ]

names(symportal) <- make.names(names(symportal), unique = TRUE)
#reanme samplenames to tubelabel species
symportal <- symportal %>%
  rename(Tubelabel_species = sample_name)


#merge new colony_long and meta
symportal_update <- merge(symportal, pcr,
                     by = c("Tubelabel_species"),
                     all = FALSE)

In [17]:
head(symportal_update)

  Tubelabel_species          fastq_fwd_file_name fastq_rev_file_name
1 012024_BEL_CBC_T1_561_OANN
2 012024_BEL_CBC_T2_587_SSID
3 012024_BEL_CBC_T2_589_SSID
4 012024_BEL_CBC_T2_603_MCAV
5 012024_BEL_CBC_T3_629_OFAV
6 012024_BEL_CBC_T3_635_OFAV
  sample_type host_phylum host_class    host_order   host_family
1 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
2 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
  host_genus   host_species ⋯ CollectionDate Species Health_status
1 Orbicella    annularis    ⋯ 1/10/24        OANN    Healthy
2 Siderastrea  sidera       ⋯ 1/12/24        SSID    Bleached_Tissue
3 Siderastrea  sidera       ⋯ 1/12/24        SSID    Bleached_Tissue
4 Montastrea   cavernosa    ⋯ 1/12/24        MCAV    Bleached_Tissue
5 Orbicella    faveolata    ⋯ 1/10/24        OFAV    Healthy
6 Orbicella    faveolata    ⋯ 1/10/24        OFAV    Healthy
  Sample_physical_location Extraction_physical_location immune_y.n Condition
1 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
2 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLB
3 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLB
4 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLP
5 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
6 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
  Date_16S Date_ITS2 Run_num
1 1_9_2026 1_21_2026 3
2 1_8_2026 1_20_2026 3
3 1_8_2026 1_20_2026 3
4 1_8_2026 1_20_2026 3
5 1_8_2026 1_20_2026 3
6 1_9_2026 1_21_2026 3

## put in file names

In [18]:
symportal_update$Tubelabel_species <- gsub("_", "-", symportal_update$Tubelabel_species)
head(symportal_update)

  Tubelabel_species          fastq_fwd_file_name fastq_rev_file_name
1 012024-BEL-CBC-T1-561-OANN
2 012024-BEL-CBC-T2-587-SSID
3 012024-BEL-CBC-T2-589-SSID
4 012024-BEL-CBC-T2-603-MCAV
5 012024-BEL-CBC-T3-629-OFAV
6 012024-BEL-CBC-T3-635-OFAV
  sample_type host_phylum host_class    host_order   host_family
1 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
2 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
  host_genus   host_species ⋯ CollectionDate Species Health_status
1 Orbicella    annularis    ⋯ 1/10/24        OANN    Healthy
2 Siderastrea  sidera       ⋯ 1/12/24        SSID    Bleached_Tissue
3 Siderastrea  sidera       ⋯ 1/12/24        SSID    Bleached_Tissue
4 Montastrea   cavernosa    ⋯ 1/12/24        MCAV    Bleached_Tissue
5 Orbicella    faveolata    ⋯ 1/10/24        OFAV    Healthy
6 Orbicella    faveolata    ⋯ 1/10/24        OFAV    Healthy
  Sample_physical_location Extraction_physical_location immune_y.n Condition
1 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
2 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLB
3 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLB
4 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          CLP
5 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
6 UML_NARWHAL_R5_B18       UML_NARWHAL_R2_B16           y          Healthy
  Date_16S Date_ITS2 Run_num
1 1_9_2026 1_21_2026 3
2 1_8_2026 1_20_2026 3
3 1_8_2026 1_20_2026 3
4 1_8_2026 1_20_2026 3
5 1_8_2026 1_20_2026 3
6 1_9_2026 1_21_2026 3

In [19]:
pathF="/scratch/workspace/caroline_desouza_uml_edu-microbe-Run3/Run3_trim/ITS2/R1"
pathR="/scratch/workspace/caroline_desouza_uml_edu-microbe-Run3/Run3_trim/ITS2/R2"

# Convert the character vector into a list
r1 <- as.data.frame(list.files(pathF))

r2 <- as.data.frame(list.files(pathR))
head(r1)

  list.files(pathF)
1 012024-BEL-CBC-T1-561-OANN_S95_R1_ITS2.fastq.gz
2 012024-BEL-CBC-T2-587-SSID_S63_R1_ITS2.fastq.gz
3 012024-BEL-CBC-T2-589-SSID_S52_R1_ITS2.fastq.gz
4 012024-BEL-CBC-T2-603-MCAV_S39_R1_ITS2.fastq.gz
5 012024-BEL-CBC-T3-629-OFAV_S35_R1_ITS2.fastq.gz
6 012024-BEL-CBC-T3-635-OFAV_S82_R1_ITS2.fastq.gz

In [20]:
fnFs = sort(list.files(pathF, pattern="_R1_ITS2.fastq", full.names = TRUE))
fnRs = sort(list.files(pathR, pattern="_R2_ITS2.fastq", full.names = TRUE))
r1$Tubelabel_species = sapply(strsplit(basename(fnFs), "_"), `[`, 1)
r2$Tubelabel_species = sapply(strsplit(basename(fnRs), "_"), `[`, 1)
head(r1)

  list.files(pathF)                               Tubelabel_species
1 012024-BEL-CBC-T1-561-OANN_S95_R1_ITS2.fastq.gz 012024-BEL-CBC-T1-561-OANN
2 012024-BEL-CBC-T2-587-SSID_S63_R1_ITS2.fastq.gz 012024-BEL-CBC-T2-587-SSID
3 012024-BEL-CBC-T2-589-SSID_S52_R1_ITS2.fastq.gz 012024-BEL-CBC-T2-589-SSID
4 012024-BEL-CBC-T2-603-MCAV_S39_R1_ITS2.fastq.gz 012024-BEL-CBC-T2-603-MCAV
5 012024-BEL-CBC-T3-629-OFAV_S35_R1_ITS2.fastq.gz 012024-BEL-CBC-T3-629-OFAV
6 012024-BEL-CBC-T3-635-OFAV_S82_R1_ITS2.fastq.gz 012024-BEL-CBC-T3-635-OFAV

In [21]:
# fill in this symportal_update$fastq_fwd_file_name  by $Tubelabel_species
#merge new colony_long and meta
symportal_update <- merge(symportal_update, r1,
                     by = c("Tubelabel_species"),
                     all = FALSE)

# fill in this symportal_update$fastq_fwd_file_name  by $Tubelabel_species
#merge new colony_long and meta
symportal_update <- merge(symportal_update, r2,
                     by = c("Tubelabel_species"),
                     all = FALSE)
head(symportal_update)

  Tubelabel_species          fastq_fwd_file_name fastq_rev_file_name
1 012024-BEL-CBC-T1-561-OANN
2 012024-BEL-CBC-T2-587-SSID
3 012024-BEL-CBC-T2-589-SSID
4 012024-BEL-CBC-T2-603-MCAV
5 012024-BEL-CBC-T3-629-OFAV
6 012024-BEL-CBC-T3-635-OFAV
  sample_type host_phylum host_class    host_order   host_family
1 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
2 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
3 coral_field Cnidaria    Hexacorallia  Scleractinia Rhizangiidae
4 coral_field Cnidaria    Hexacorallia  Scleractinia Montastraeidae
5 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
6 coral_field Cnidaria    Hexacorallia  Scleractinia Merulinidae
  host_genus   host_species ⋯ Health_status   Sample_physical_location
1 Orbicella    annularis    ⋯ Healthy         UML_NARWHAL_R5_B18
2 Siderastrea  sidera       ⋯ Bleached_Tissue UML_NARWHAL_R5_B18
3 Siderastrea  sidera       ⋯ Bleached_Tissue UML_NARWHAL_R5_B18
4 Montastrea   cavernosa    ⋯ Bleached_Tissue UML_NARWHAL_R5_B18
5 Orbicella    faveolata    ⋯ Healthy         UML_NARWHAL_R5_B18
6 Orbicella    faveolata    ⋯ Healthy         UML_NARWHAL_R5_B18
  Extraction_physical_location immune_y.n Condition Date_16S Date_ITS2 Run_num
1 UML_NARWHAL_R2_B16           y          Healthy   1_9_2026 1_21_2026 3
2 UML_NARWHAL_R2_B16           y          CLB       1_8_2026 1_20_2026 3
3 UML_NARWHAL_R2_B16           y          CLB       1_8_2026 1_20_2026 3
4 UML_NARWHAL_R2_B16           y          CLP       1_8_2026 1_20_2026 3
5 UML_NARWHAL_R2_B16           y          Healthy   1_8_2026 1_20_2026 3
6 UML_NARWHAL_R2_B16           y          Healthy   1_9_2026 1_21_2026 3
  list.files(pathF)
1 012024-BEL-CBC-T1-561-OANN_S95_R1_ITS2.fastq.gz
2 012024-BEL-CBC-T2-587-SSID_S63_R1_ITS2.fastq.gz
3 012024-BEL-CBC-T2-589-SSID_S52_R1_ITS2.fastq.gz
4 012024-BEL-CBC-T2-603-MCAV_S39_R1_ITS2.fastq.gz
5 012024-BEL-CBC-T3-629-OFAV_S35_R1_ITS2.fastq.gz
6 012024-BEL-CBC-T3-635-OFAV_S82_R1_ITS2.fastq.gz
  list.files(pathR)
1 012024-BEL-CBC-T1-561-OANN_S95_R2_ITS2.fastq.gz
2 012024-BEL-CBC-T2-587-SSID_S63_R2_ITS2.fastq.gz
3 012024-BEL-CBC-T2-589-SSID_S52_R2_ITS2.fastq.gz
4 012024-BEL-CBC-T2-603-MCAV_S39_R2_ITS2.fastq.gz
5 012024-BEL-CBC-T3-629-OFAV_S35_R2_ITS2.fastq.gz
6 012024-BEL-CBC-T3-635-OFAV_S82_R2_ITS2.fastq.gz

In [23]:
write.csv(symportal_update, file="/home/caroline_desouza_uml_edu/run3_symportal_update.csv")